module.exports = [
  { errorCode: 1016, errorMessage: "License Error: Could not find license." },
  { errorCode: 3000, errorMessage: "Unknown error" },
  { errorCode: 3001, errorMessage: "Unsupported manifest format" },
  { errorCode: 3002, errorMessage: "Segment contains no data" },
  { errorCode: 3003, errorMessage: "Corrupt tfdt version" },
  { errorCode: 3004, errorMessage: "No URL for segment found" },
  { errorCode: 3005, errorMessage: "No URL to manifest given" },
  { errorCode: 3006, errorMessage: "Could not load manifest, got HTTP status code " },
  { errorCode: 3011, errorMessage: "DRM: License request failed with HTTP status " },
  { errorCode: 3012, errorMessage: "DRM: Invalid header name/value pair for PlayReady license request" },
  { errorCode: 3013, errorMessage: "DRM: Key or KeyID is missing" },
  { errorCode: 3014, errorMessage: "DRM: Key size not supported" },
  { errorCode: 3016, errorMessage: "DRM: Unable to instantiate a key system supporting the required combinations" },
  { errorCode: 3017, errorMessage: "DRM: Unable to create or initialize key session" },
  { errorCode: 3018, errorMessage: "DRM: Failed to create and initialize a MediaKeys object" },
  { errorCode: 3019, errorMessage: "DRM: Key or KeyID is missing" },
  { errorCode: 3020, errorMessage: "DRM: Key Error" },
];
